### PR TITLE
Reduce layer count for docker image

### PR DESCRIPTION
**Pull request by TroyDota**

### CODE REVIEW

**Review by AnatoleAM — CHANGES_REQUESTED** [review]
Tested this locally and the build fails

```
[+] Building 1.6s (4/4) FINISHED                                                                                                                                                                                                                                                                                                                           
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                  0.0s
 => => transferring dockerfile: 38B                                                                                                                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                                     0.1s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                       0.0s
 => CANCELED [internal] load metadata for docker.io/library/alpine:3.14                                                                                                                                                                                                                                                                               1.5s
 => ERROR [internal] load metadata for docker.io/library/golang:1.16.5-alpine3.14                                                                                                                                                                                                                                                                     1.5s
------
 > [internal] load metadata for docker.io/library/golang:1.16.5-alpine3.14:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:a8409dff6597f2ef5f7ecd3c672671bb2af9a390073efd74f95c54aa41cba22a: not found
```

**Comment by TroyDota** [comment]
ok, ill look

**Comment by TroyDota** [comment]
https://forums.docker.com/t/golang-simple-tag-golang-1-16-5-alpine3-14-exists-but-no-manifest-available/111315 Weird.

**Review by AnatoleAM — APPROVED** [review]
All good

**Pull request merged**
