### PR TITLE
Added `profile_picture_id` to the User Object, Payload Example.

### PR DESCRIPTION
**Pull request by mmattbtw**

### CODE REVIEW

**Comment by AnatoleAM** [comment]
This field is not very useful, and thus I don't think it should be documented.

**Comment by mmattbtw** [comment]
I think it could be useful for people building third party applications that sign in with Twitch, and want the user to keep the same Profile Picture as they are seen on Twitch. Also, I believe that if it wasn't documented, people that would want to use it wouldn't see it in the documentation, and they pinged the API with a request and saw it, and didn't know how to use it, they'd probably have to go figure it out themselves rather then giving them the information upfront, which is what documentation is used for.

**Comment by AnatoleAM** [comment]
Just for reference

- This repository will be archived and never touched again in the next few days (the codebase of both v2 and v3 will be at [SevenTV/GQL](github.com/SevenTV/GQL) [SevenTV/REST](github.com/SevenTV/REST) [SevenTVCommon](github.com/SevenTV/Common))
- This is a very niche use case for an implementation. I don't actually remember why this field was added in the user response, but animated avatars are implemented via the `/v2/cosmetics/avatars` route, not this.
- API V3 will likely have a completely different method of implementation for profile pictures, so if anyone was planning on implementing them I would much rather they wait for that
- Proper, full documentation is planned. Again we aren't gonna push v2 too much at this point since v3 will change everything.

**Comment by mmattbtw** [comment]
Understandable. I wasn't aware that V2's deprecation was happening so soon, or that the other route existed.

**Pull request closed without merging**
