### PR TITLE
API/REST - Endpoint to convert WEBP emotes to GIF

### PR DESCRIPTION
**Pull request by AnatoleAM**
Adding an endpoint which takes an emote ID and converts the CDN image into a GIF for discord compatibility

### CODE REVIEW

**Comment by AnatoleAM** [comment]
xd

**Comment by TroyDota** [comment]
Uhm

**Comment by TroyDota** [comment]
Wtf just use cloudflare we pay for premium for a reason broke back

**Comment by AnatoleAM** [comment]
> Wtf just use cloudflare we pay for premium for a reason broke back

how ??

**Pull request merged**
